export enum AppointmentStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PATIENT_WAITING = 'PATIENT_WAITING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  NEXT_PATIENT_NOTIFIED = 'NEXT_PATIENT_NOTIFIED'
}
