export enum FileTypeEnum {
  MEDICAL_REPORT = 'MEDICAL_REPORT',
  PRESCRIPTION_PDF = 'PRESCRIPTION_PDF',
  DOCTOR_CREDENTIAL = 'DOCTOR_CREDENTIAL',
  PATIENT_DOCUMENT = 'PATIENT_DOCUMENT',
  OTHER = 'OTHER'
}
